### ISSUE TITLE
License for this ebook?

### ISSUE THREAD

**Issue by billryan** [DONGChuan/Java_Interview_question#2]
I want to contribute this ebook, but I don't see any license for this ebook. :(
https://github.com/billryan/algorithm-exercise is my notes of algorithm, hope the license or structure of the ebook can help you.

**Comment by DONGChuan** [comment]
Hi Bill

Thanks for contacting me. For sure, you are welcome to join us. We are now fighting with another book "Gradle User Guide". So now I dont spend time yet on java interview. And I was ill this weekend. 

I will take a look at infos you sent to me tmrw afternoon and talk with you ASAP :P

Cheers,
Chuan DONG

**Comment by billryan** [comment]
Take care.

**Comment by DONGChuan** [comment]
Hi Bill,

I already take a look at the license you used. I will add the same later :D In fact, I m very new to all these things, so didnt care much about it.

To contribute to this ebook,
I would give you the permission on gitbook and on github for sure. If you need any other information, feel free to contact me. On my side, it's french timezone, so I m not always available. 

Feel free to update everything. Let's contribute to the world and learn from each other :D

Cheers,
Chuan DONG

**Comment by DONGChuan** [comment]
I added license you used. Done.

What's more, in fact, in the settings of gitbook, we could choose license directly. I chose Apache 2.0. But it seems not to be shown on the main page :D Any more. I m so looking forward to your updating
