### ISSUE TITLE
关于接口 interface 的疑问

### ISSUE THREAD

**Issue by ningt** [DONGChuan/Java_Interview_question#4]
接口的特点
- 不能实例化
- 没有构造体
- 所有方法都是抽象的 public static

`所有方法都是抽象的 public static` - 什么是 `抽象的 public static`？我觉得这个说法好像不太准确。

下面是我看到的关于接口 interface 特点的一些介绍
- You cannot instantiate an interface.
- An interface does not contain any constructors.
- All of the methods in an interface are abstract.
- An interface cannot contain instance fields. The only fields that can appear in an interface must be declared both static and final.
- An interface is not extended by a class; it is implemented by a class.
- An interface can extend multiple interfaces.

readme 里关于 contribution 的的链接挂掉了 :)

**Comment by DONGChuan** [comment]
哦哦 我回去修改下 我当时就是自己随手记的 这里应该是指接口里面的所有方法默认/隐式都是 public static 的 我周末整理下 ~ 谢谢啦！

**Comment by DONGChuan** [comment]
已经更新 interface 部分声明以及贡献方式的说明！ 现在 gitbook 的在线编辑功能太好了 。。
