### ISSUE TITLE
There is something wrong in the 'interface.md'

### ISSUE THREAD

**Issue by ruanhang1993** [DONGChuan/Java_Interview_question#8]
The sentence "所有方法都是抽象的 (abstract).同时也是隐式的 public static. 也就是说声明时, 可以省略 public static." should be changed to "所有方法都是抽象的 (abstract).同时也是隐式的 public. 也就是说声明时, 可以省略 public abstract.".
The static methods in Java need a method body.

**Comment by DONGChuan** [comment]
感谢提醒 已修复
